\set ON_ERROR_STOP on
BEGIN;
INSERT INTO auth.users(id) VALUES('00000000-0000-0000-0000-000000009001'),('00000000-0000-0000-0000-000000009002');
INSERT INTO user_roles(user_id,role) VALUES('00000000-0000-0000-0000-000000009001','admin');
DO $$ DECLARE oid uuid; manual uuid; paid uuid; v integer; ref text; r jsonb; BEGIN
 PERFORM set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000009001',true);
 INSERT INTO orders(customer_name,phone,order_type,total_cents,payment_method,payment_state) VALUES('Test','3001234567','pickup',10000,'online','pending') RETURNING id INTO oid;
 ref:='finance-'||oid;
 INSERT INTO payment_attempts(order_id,reference,environment,amount_cop) VALUES(oid,ref,'test',10000);
 PERFORM order_action(oid,0,'cancel','Customer cancelled');
 IF (SELECT financial_attention_at FROM orders WHERE id=oid) IS NOT NULL THEN RAISE EXCEPTION 'unpaid cancellation alerted'; END IF;
 PERFORM order_payment_apply(ref,'finance-provider',1000000,'COP','test','APPROVED','finance-event');
 IF NOT EXISTS(SELECT 1 FROM orders WHERE id=oid AND status='cancelled' AND payment_state='paid' AND financial_attention_at IS NOT NULL AND financial_acknowledged_at IS NULL) THEN RAISE EXCEPTION 'late approval lost'; END IF;
 PERFORM order_payment_apply(ref,'finance-provider',1000000,'COP','test','APPROVED','finance-event-duplicate');
 IF (SELECT count(*) FROM order_events WHERE order_id=oid AND kind='financial_attention_required')<>1 THEN RAISE EXCEPTION 'duplicate incident'; END IF;
 SELECT version INTO v FROM orders WHERE id=oid;
 PERFORM set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000009002',true);
 BEGIN PERFORM order_action(oid,v,'acknowledge_financial',''); RAISE EXCEPTION 'nonadmin acknowledged'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'forbidden' THEN RAISE; END IF; END;
 PERFORM set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000009001',true);
 PERFORM order_action(oid,v,'acknowledge_financial','Review opened');
 BEGIN PERFORM order_action(oid,v,'acknowledge_financial',''); RAISE EXCEPTION 'stale acknowledgement accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'version_conflict' THEN RAISE; END IF; END;
 IF NOT EXISTS(SELECT 1 FROM orders WHERE id=oid AND status='cancelled' AND payment_state='paid' AND financial_acknowledged_at IS NOT NULL AND financial_resolved_at IS NULL) THEN RAISE EXCEPTION 'ack resolved money'; END IF;
 SELECT version INTO v FROM orders WHERE id=oid;
 BEGIN PERFORM order_action(oid,v,'resolve_financial','Pretend refunded'); RAISE EXCEPTION 'online manual resolution accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'invalid_financial_resolution' THEN RAISE; END IF; END;
 r:=order_refund_request(oid,v,'Cancelled payment');
 PERFORM order_refund_claim((r->>'id')::uuid);
 PERFORM order_refund_apply((r->>'id')::uuid,'finance-refund','finance-provider',1000000,'PENDING');
 IF (SELECT financial_resolved_at FROM orders WHERE id=oid) IS NOT NULL THEN RAISE EXCEPTION 'pending refund resolved'; END IF;
 PERFORM order_refund_apply((r->>'id')::uuid,'finance-refund','finance-provider',1000000,'APPROVED');
 IF NOT EXISTS(SELECT 1 FROM orders WHERE id=oid AND status='cancelled' AND payment_state='refunded' AND financial_resolved_at IS NOT NULL) THEN RAISE EXCEPTION 'verified refund not resolved'; END IF;
 INSERT INTO orders(customer_name,phone,order_type,total_cents,payment_method,payment_state) VALUES('Paid','3001234567','pickup',10000,'online','paid') RETURNING id INTO paid;
 PERFORM order_action(paid,0,'cancel','Cancel already paid');
 IF (SELECT financial_attention_at FROM orders WHERE id=paid) IS NULL THEN RAISE EXCEPTION 'paid cancellation lost'; END IF;
 INSERT INTO orders(customer_name,phone,order_type,total_cents,payment_method,payment_state) VALUES('Manual','3001234567','pickup',10000,'cash','paid') RETURNING id INTO manual;
 PERFORM order_action(manual,0,'cancel','Cash received');
 PERFORM order_action(manual,1,'resolve_financial','Customer confirmed cash returned; receipt recorded');
 IF NOT EXISTS(SELECT 1 FROM orders WHERE id=manual AND status='cancelled' AND payment_state='paid' AND financial_resolved_at IS NOT NULL) THEN RAISE EXCEPTION 'manual resolution changed money or reopened'; END IF;
 IF NOT EXISTS(SELECT 1 FROM order_events WHERE order_id=manual AND kind='resolve_financial' AND actor_id='00000000-0000-0000-0000-000000009001') THEN RAISE EXCEPTION 'manual resolution not audited'; END IF;
END $$;
ROLLBACK;
